import type { Intensity } from "../types";

// Category for the classic A→Z naming drill. Players rotate, each saying
// something from the category starting with A, B, C, … Miss your letter = drink.

export const categories: Record<Intensity, string[]> = {
  mild: [
    "Countries",
    "Foods",
    "Animals",
    "Movies",
    "Bands",
    "Cities",
    "Board games",
    "Cartoons",
    "Desserts",
    "Dog breeds",
    "Colors",
    "Brands",
    "Sports",
    "Types of car",
    "Capitals",
    "Words you'd text your mom",
  ],
  spicy: [
    "First-date ideas",
    "Flirty text openers",
    "Pickup lines",
    "Dating-app red flags",
    "Things you wear on a date",
    "Date-night movies",
    "Celebrity crushes",
    "Ex types",
    "Reasons to stay the night",
    "Places to kiss",
    "Songs you'd sext to",
    "Places you've made out",
    "Things you'd never split on a first date",
    "Rom-coms",
    "Breakup excuses",
    "Things you text at 2am",
  ],
  extreme: [
    "Kinks",
    "Places to have sex",
    "Sex positions",
    "Things said mid-act",
    "Toys",
    "Reasons you faked it",
    "Body parts",
    "Dirty pet names",
    "Things that turn you off",
    "Things that turn you on",
    "Songs on a hookup playlist",
    "Words you've moaned",
    "Porn categories",
    "Lies you've told in bed",
    "Kinks you haven't tried but would",
  ],
  chaos: [
    "Sex acts nobody wants to admit",
    "Fluids",
    "Kinks named after people",
    "Moans you've let out",
    "Names you'd moan by mistake",
    "Places you've had sex you shouldn't have",
    "Safewords",
    "Nicknames for genitals",
    "Reasons you've stopped mid-act",
    "Filthy confessions",
    "Unusual turn-ons",
    "Dirty texts",
    "Celebrity threesome picks",
    "Things you'd never repeat",
    "Sex-tape co-stars",
    "Positions you've ruined your back on",
  ],
};
