import type { Intensity } from "../types";

export const challenges: Record<Intensity, string[]> = {
  mild: [
    "Do your best catwalk across the room — or drink.",
    "Name 5 brands of cereal in 10 seconds — or drink.",
    "Speak in an accent until your next turn — or drink.",
    "Let another player post on your story — or take 2 drinks.",
    "Do 10 push-ups — or drink.",
    "Eat a spoon of something from the kitchen blindfolded — or drink twice.",
    "Swap phones with another player for 60 seconds — or drink.",
    "Imitate the last person who texted you — or drink.",
    "Do the worm for 5 seconds — or drink.",
    "Beatbox for 15 seconds — or drink.",
  ],
  spicy: [
    "Text your crush a line of a love song — or drink 3.",
    "Let someone go through your DMs for 30 seconds — or drink 3.",
    "Kiss the person to your left on the cheek — or drink twice.",
    "Take a body shot off another player — or drink 3.",
    "Let the group pick a selfie and post it — or drink 3.",
    "Show the last nude in your gallery (or swear you have none) — or drink 3.",
    "Sit on another player's lap for 2 rounds — or drink twice.",
    "Demonstrate your signature dance move solo — or drink twice.",
    "Let another player write something in lipstick on your arm — or drink twice.",
    "Reveal your phone passcode — or drink 3.",
  ],
  chaos: [
    "Make out with the player of the group's choice for 30 seconds — or drink 7.",
    "Remove two items of clothing. Group picks which — or drink 7.",
    "Give the player of the group's choice a 30-second lap dance — or drink 7.",
    "Sit on someone's lap for the next 4 rounds. Group picks — or drink 6.",
    "Let the group blindfold you. Three players kiss you somewhere — or drink 7.",
    "Take body shots off two different players — or drink 7.",
    "Trade entire outfits with the player across from you — or each drink 5.",
    "Send an unscripted thirst voice note to your last hookup. Group listens — or drink 7.",
    "Let the group write three filthy words on your body in marker — or drink 7.",
    "Describe, in detail, your wildest fantasy to the group — or drink 7.",
    "Let the player on your right choose one piece of your clothing — they get to keep it until the end — or drink 6.",
    "Spin the bottle: kiss whoever it lands on for 10 seconds, no exceptions — or drink 7.",
    "Give the person of the group's choice a neck kiss that lasts until someone calls time — or drink 7.",
    "Reveal your phone passcode AND open your DMs for 60 seconds — or drink 8.",
    "Let the group tie your hands. They stay tied for the next 5 rounds — or drink 6.",
  ],
  extreme: [
    "Make out with the player of the group's choice for 10 seconds — or drink 5.",
    "Remove one piece of clothing — or drink 4.",
    "Give another player a lap dance for 15 seconds — or drink 5.",
    "Let the group read your last 10 DMs out loud — or drink 5.",
    "Send a thirst trap to the last person you matched with — or drink 5.",
    "Pick a player. Trade shirts right now — or both of you drink 3.",
    "Let the group blindfold you and pick someone to kiss your neck — or drink 5.",
    "Confess your filthiest fantasy to the group — or drink 5.",
    "Take a body shot off the player of the group's choice — or drink 5.",
    "Let another player tie your hands for 2 rounds — or drink 4.",
  ],
};
