import type { Intensity } from "../types";

// Each round: show the word, collect fake definitions, include the real one,
// group votes on which is real. Intensity shifts the vocabulary.

export interface FictionaryWord {
  word: string;
  definition: string;
}

export const words: Record<Intensity, FictionaryWord[]> = {
  mild: [
    { word: "borborygmus", definition: "The rumbling or gurgling noise made by the movement of fluid and gas in the intestines." },
    { word: "petrichor", definition: "The pleasant, earthy smell produced when rain falls on dry soil." },
    { word: "defenestration", definition: "The act of throwing someone or something out of a window." },
    { word: "tittynope", definition: "A small leftover quantity of food or drink." },
    { word: "grawlix", definition: "The symbols used in comics to represent swearing, like @#$%&." },
    { word: "snollygoster", definition: "A shrewd, unprincipled person, especially a politician." },
    { word: "bumfuzzle", definition: "To confuse or perplex someone." },
    { word: "flummadiddle", definition: "Something utterly useless or nonsense." },
    { word: "callipygian", definition: "Having shapely or well-formed buttocks." },
    { word: "cockalorum", definition: "A small, self-important man." },
    { word: "lollygag", definition: "To spend time aimlessly; dawdle." },
    { word: "collywobbles", definition: "A feeling of uneasiness in the stomach, especially from anxiety." },
    { word: "gardyloo", definition: "A warning once shouted before tossing dirty water out a window." },
    { word: "widdershins", definition: "In a direction contrary to the sun's course; counterclockwise." },
    { word: "brouhaha", definition: "A noisy and overexcited reaction or response." },
    { word: "hornswoggle", definition: "To get the better of someone by cheating or deception." },
  ],
  spicy: [
    { word: "callipygian", definition: "Having shapely or well-formed buttocks." },
    { word: "limerence", definition: "The state of being obsessively infatuated with someone." },
    { word: "philander", definition: "To readily or frequently enter into casual sexual affairs." },
    { word: "concupiscent", definition: "Filled with sexual desire; lustful." },
    { word: "frisson", definition: "A sudden strong feeling of excitement or fear; a thrill." },
    { word: "osculation", definition: "The action or act of kissing." },
    { word: "anosognosia", definition: "A condition in which a person is unaware of their own disability." },
    { word: "saudade", definition: "A deep emotional state of melancholic longing for something absent." },
    { word: "susurrus", definition: "A soft murmuring or rustling sound, like a whisper." },
    { word: "nyctophilia", definition: "A love or preference for night and darkness." },
    { word: "gobsmacked", definition: "Utterly astonished; astounded." },
    { word: "nudiustertian", definition: "Pertaining to the day before yesterday." },
    { word: "mondegreen", definition: "A misheard lyric or phrase that changes the meaning." },
    { word: "agastopia", definition: "Admiration of a particular part of someone's body." },
    { word: "pogonophobia", definition: "The fear of beards." },
    { word: "frotteur", definition: "A person who gains sexual gratification from rubbing against strangers." },
  ],
  extreme: [
    { word: "frotteur", definition: "A person who gains sexual gratification from rubbing against strangers." },
    { word: "avisodomy", definition: "The act of engaging in sexual relations with a bird." },
    { word: "agalmatophilia", definition: "Sexual attraction to statues, mannequins, or other figures." },
    { word: "nymphomania", definition: "Compulsive or excessive sexual desire, historically in women." },
    { word: "satyriasis", definition: "Excessive, often uncontrollable sexual desire in a man." },
    { word: "ithyphallic", definition: "Relating to the erect phallus carried in ancient Greek festivals." },
    { word: "priapism", definition: "A prolonged, often painful erection not caused by sexual arousal." },
    { word: "troilism", definition: "Sexual activity involving three people." },
    { word: "vorarephilia", definition: "A fetish involving the fantasy of being eaten or eating another." },
    { word: "salirophilia", definition: "A paraphilia involving arousal from dirtying or disheveling a partner." },
    { word: "cunctator", definition: "One who delays or procrastinates; a slowcoach." },
    { word: "pandiculation", definition: "The act of stretching and yawning, especially on waking." },
    { word: "quidnunc", definition: "A person who is eager to know the latest news or gossip." },
    { word: "ultracrepidarian", definition: "One who gives opinions on matters beyond their knowledge." },
    { word: "ninnyhammer", definition: "A fool or simpleton." },
    { word: "mumpsimus", definition: "A person who obstinately adheres to a wrong idea." },
  ],
  chaos: [
    { word: "niplostoria", definition: "The study of the history and cultural meaning of nipples." },
    { word: "dendrophilia", definition: "Sexual attraction to trees or wooden objects." },
    { word: "formicophilia", definition: "Arousal caused by insects crawling on the body." },
    { word: "klismaphilia", definition: "Sexual arousal derived from receiving enemas." },
    { word: "odaxelagnia", definition: "The sexual gratification gained from biting or being bitten." },
    { word: "hybristophilia", definition: "Attraction to people who have committed serious crimes." },
    { word: "teratophilia", definition: "Sexual attraction to those with physical deformities." },
    { word: "acucullophallia", definition: "The condition of having a circumcised penis, historically." },
    { word: "pygophilia", definition: "An intense sexual attraction to the buttocks." },
    { word: "coprolalia", definition: "The involuntary use of obscene or vulgar language." },
    { word: "xenoglossy", definition: "The apparent ability to speak a language one has never learned." },
    { word: "chremamorphism", definition: "Attributing the characteristics of objects to humans." },
    { word: "misophonia", definition: "A hatred of specific sounds, like chewing or breathing." },
    { word: "dysania", definition: "The difficulty of getting out of bed in the morning." },
    { word: "kakistocracy", definition: "Government by the least qualified or most unprincipled citizens." },
    { word: "witzelsucht", definition: "A tendency to make jokes or inappropriate witticisms." },
  ],
};
