import type { Intensity } from "../types";

// "Name 3 X in 5 seconds!" — rapid-fire category prompts.

export const prompts: Record<Intensity, string[]> = {
  mild: [
    "Name 3 breakfast foods.",
    "Name 3 Disney princesses.",
    "Name 3 types of dance.",
    "Name 3 board games.",
    "Name 3 countries that start with A.",
    "Name 3 Adam Sandler movies.",
    "Name 3 cereals.",
    "Name 3 pizza toppings you'd actually eat.",
    "Name 3 celebrities you've had a crush on.",
    "Name 3 reasons to skip work.",
    "Name 3 songs from the 2000s.",
    "Name 3 things on your phone right now.",
    "Name 3 worst first-date ideas.",
    "Name 3 of your exes' names.",
    "Name 3 chores you hate.",
    "Name 3 movies that made you cry.",
    "Name 3 fast food chains.",
    "Name 3 people in this room.",
    "Name 3 podcasts you've listened to.",
    "Name 3 things older than you.",
  ],
  spicy: [
    "Name 3 people you've kissed.",
    "Name 3 places you've hooked up.",
    "Name 3 things that instantly turn you on.",
    "Name 3 celebrity hall-passes.",
    "Name 3 qualities in a one-night stand.",
    "Name 3 songs that make you want to hook up.",
    "Name 3 red flags you've ignored.",
    "Name 3 awful pickup lines.",
    "Name 3 dates that ended badly.",
    "Name 3 reasons you'd leave a date early.",
    "Name 3 TV shows you'd sext your crush about.",
    "Name 3 things you'd never admit sober.",
    "Name 3 types of people you've dated.",
    "Name 3 songs for your hookup playlist.",
    "Name 3 body parts you find underrated.",
    "Name 3 ways to flirt without saying a word.",
    "Name 3 texts you've sent drunk.",
    "Name 3 outfits that scream 'take me home'.",
    "Name 3 ex names you'd never say out loud.",
    "Name 3 apps you'd delete before a partner checked your phone.",
  ],
  extreme: [
    "Name 3 kinks you've tried.",
    "Name 3 positions you've actually used.",
    "Name 3 places you've had sex.",
    "Name 3 things you've done for someone hot.",
    "Name 3 times you've faked it.",
    "Name 3 celebrities you'd do anything with.",
    "Name 3 people in this room, ranked by who you'd pick.",
    "Name 3 worst sex injuries you've heard of.",
    "Name 3 filthy things you've searched online.",
    "Name 3 nicknames for a penis.",
    "Name 3 nicknames for a vagina.",
    "Name 3 taboos you've broken.",
    "Name 3 people you'd never admit you've slept with.",
    "Name 3 things that instantly kill the mood.",
    "Name 3 lies you've told mid-hookup.",
    "Name 3 fantasies you've never shared.",
    "Name 3 sex toys you'd try.",
    "Name 3 ex-partners' worst habits in bed.",
    "Name 3 bedroom dealbreakers.",
    "Name 3 things you'd do for a night with your celebrity crush.",
  ],
  chaos: [
    "Name 3 kinks you haven't tried but would.",
    "Name 3 people you've fantasized about in this room.",
    "Name 3 sex acts you've sworn off.",
    "Name 3 exes you'd sleep with again for the right price.",
    "Name 3 most expensive things you'd do sexually for money.",
    "Name 3 places sex should be legal but isn't.",
    "Name 3 body fluids that turn you off.",
    "Name 3 scenarios you've gotten off to this month.",
    "Name 3 people in this room you'd invite to a threesome.",
    "Name 3 hardest nos in the bedroom.",
    "Name 3 things you'd let a stranger do for $1000.",
    "Name 3 times you orgasmed when you shouldn't have.",
    "Name 3 names you've moaned by mistake.",
    "Name 3 kinks that used to disgust you until you tried them.",
    "Name 3 places you've been caught mid-act.",
    "Name 3 fluids you've accidentally swallowed.",
    "Name 3 people who probably have nudes of you.",
    "Name 3 things you've done for a nut.",
    "Name 3 safe words.",
    "Name 3 moans you've faked.",
  ],
};
