import type { Intensity } from "../types";

export const prompts: Record<Intensity, string[]> = {
  mild: [
    "What's your biggest insecurity?",
    "What's your worst habit?",
    "What's a compliment you can't accept?",
    "Who do you envy the most in this room?",
    "What's the last lie you told someone here?",
    "What's something you'd change about yourself?",
    "What's a friendship you regret losing?",
    "What's the meanest thing you've ever said?",
    "What are you most afraid of?",
    "What's your biggest regret from the last year?",
  ],
  spicy: [
    "What's the last thing you thought about before falling asleep?",
    "Who in this room do you find most attractive?",
    "What's the last hookup you had?",
    "What's a secret crush you've had here?",
    "What's the horniest you've ever been?",
    "What's your ideal hookup scenario?",
    "Who was your best kiss?",
    "What's the flirtiest text you've sent this month?",
    "What turns you on instantly?",
    "What's the naughtiest thing you've done sober?",
  ],
  chaos: [
    "Tell us, in detail, about your most recent hookup.",
    "What's the wildest thing you've done sober, within the last year?",
    "Describe your darkest fantasy — not the PG version.",
    "Who in this room would you pick for a threesome partner and why?",
    "What's the filthiest thing you've ever said out loud in bed?",
    "What's the most scandalous thing on your phone right now, and we get to see it.",
    "What's something you've done that your parents would disown you for?",
    "If the group picked a stranger for you to go home with tonight, would you?",
    "What's the most toxic thing you've ever done for someone you wanted?",
    "What's the last rule you broke for a hookup?",
    "What's the most people you've kissed in 24 hours?",
    "Describe the wildest place you've ever hooked up — and why you'd do it again.",
  ],
  extreme: [
    "Who in this room would you sleep with if there were no consequences?",
    "Describe the best sex of your life.",
    "What's your darkest kink?",
    "What's the most people you've had in bed at once?",
    "What's the dirtiest thing you've ever said to someone?",
    "Have you ever slept with someone you shouldn't have? Who?",
    "What's a fantasy you'd never admit to sober?",
    "What's the nastiest text on your phone right now?",
    "What's the riskiest place you've hooked up?",
    "Who in this room do you think about when you're alone?",
  ],
};
