import type { Intensity } from "../types";

export const prompts: Record<Intensity, string[]> = {
  mild: [
    "Most likely to become famous.",
    "Most likely to forget their own birthday.",
    "Most likely to cry at a wedding.",
    "Most likely to move to another country on a whim.",
    "Most likely to get lost on the way home.",
    "Most likely to ghost a group chat.",
    "Most likely to own 10 cats.",
    "Most likely to survive a zombie apocalypse.",
    "Most likely to start a cult.",
    "Most likely to talk to a stranger on the street.",
  ],
  spicy: [
    "Most likely to sleep with their ex again.",
    "Most likely to have a secret dating profile.",
    "Most likely to sext during a work meeting.",
    "Most likely to kiss a stranger tonight.",
    "Most likely to have hooked up with someone in this room.",
    "Most likely to flirt to get out of a ticket.",
    "Most likely to go home with the bartender.",
    "Most likely to have a secret OnlyFans.",
    "Most likely to get caught hooking up in public.",
    "Most likely to send a risky text right now.",
  ],
  chaos: [
    "Most likely to hook up with two people in this room.",
    "Most likely to break a bed.",
    "Most likely to have a sex tape hidden somewhere.",
    "Most likely to sleep with a stranger tonight.",
    "Most likely to have hooked up with someone in this room in the last 6 months.",
    "Most likely to own something illegal in at least one country.",
    "Most likely to have a safe word.",
    "Most likely to have hooked up at a funeral, wedding, or family event.",
    "Most likely to date three people at once and juggle it well.",
    "Most likely to be into something their partner would be shocked by.",
    "Most likely to have filmed it.",
    "Most likely to have a type that is 'anyone who says yes'.",
    "Most likely to hook up with the host of this party before sunrise.",
    "Most likely to ghost after a very good night.",
  ],
  extreme: [
    "Most likely to have a threesome.",
    "Most likely to cheat and never get caught.",
    "Most likely to hook up at this party.",
    "Most likely to have an onlyfans and not tell anyone.",
    "Most likely to sleep with a coworker.",
    "Most likely to be into something wild in bed.",
    "Most likely to have slept with the most people in this room.",
    "Most likely to hook up with a friend's ex.",
    "Most likely to bring home two people at once.",
    "Most likely to own a 'toy' collection.",
  ],
};
