import type { Intensity } from "../types";

export const prompts: Record<Intensity, string[]> = {
  mild: [
    "Never have I ever cried at a Pixar movie.",
    "Never have I ever lied about my age.",
    "Never have I ever pretended to be sick to skip work or school.",
    "Never have I ever stalked an ex online this week.",
    "Never have I ever fallen asleep in a public place.",
    "Never have I ever broken a bone.",
    "Never have I ever been in a physical fight.",
    "Never have I ever re-gifted something.",
    "Never have I ever snooped through someone's phone.",
    "Never have I ever sent a text to the wrong person.",
  ],
  spicy: [
    "Never have I ever kissed someone in this room.",
    "Never have I ever sent a nude.",
    "Never have I ever hooked up on a first date.",
    "Never have I ever faked one.",
    "Never have I ever had a friends-with-benefits situation.",
    "Never have I ever kissed someone whose name I didn't know.",
    "Never have I ever been caught in the act.",
    "Never have I ever had a crush on a friend's partner.",
    "Never have I ever hooked up in a car.",
    "Never have I ever had a one-night stand.",
  ],
  chaos: [
    "Never have I ever hooked up with more than one person in the same night.",
    "Never have I ever been filmed during it — with or without knowing.",
    "Never have I ever hooked up with someone in this room's ex.",
    "Never have I ever fantasized about someone in this room during it with someone else.",
    "Never have I ever been paid for — or tipped — for something flirty.",
    "Never have I ever had a safe word I actually had to use.",
    "Never have I ever hooked up with someone whose name I couldn't remember the next day.",
    "Never have I ever been walked in on and kept going.",
    "Never have I ever slept with a friend's partner.",
    "Never have I ever broken furniture during it.",
    "Never have I ever hooked up with two friends and neither knows.",
    "Never have I ever asked a stranger back to my place the same night I met them — more than twice.",
    "Never have I ever sent the exact same flirty message to more than one person on the same night.",
    "Never have I ever kept a souvenir from a hookup.",
  ],
  extreme: [
    "Never have I ever had a threesome.",
    "Never have I ever cheated on someone.",
    "Never have I ever hooked up with someone in this room.",
    "Never have I ever slept with a coworker.",
    "Never have I ever paid for — or been paid for — a date's outcome.",
    "Never have I ever been tied up.",
    "Never have I ever hooked up with someone more than 10 years older or younger.",
    "Never have I ever sent a voice note I'd die if anyone else heard.",
    "Never have I ever hooked up in a public place and almost got caught.",
    "Never have I ever kept a hookup a secret from my best friend.",
  ],
};
