import type { Intensity } from "../types";

export const prompts: Record<Intensity, string[]> = {
  mild: [
    "Who here is the worst driver?",
    "Who's most likely to embarrass themselves at karaoke?",
    "Who gives the worst gifts?",
    "Who's the biggest drama queen?",
    "Who lies the most?",
    "Who has the worst taste in music?",
    "Who would last the least in a silent retreat?",
    "Who talks too much about their ex?",
    "Who's the pettiest in the group?",
    "Who's most likely to fake an accent abroad?",
  ],
  spicy: [
    "Who's the best kisser in the room?",
    "Who have you secretly thought about in this room?",
    "Who flirts the most without realizing?",
    "Who has the best body here?",
    "Who would you switch partners with for a night?",
    "Who's most likely to sleep with a stranger?",
    "Who has the most scandalous DMs?",
    "Who's the most uptight about hookups?",
    "Who sends the best flirty texts?",
    "Who's hiding the biggest crush in this room?",
  ],
  chaos: [
    "Who here would you let tie you up?",
    "Who in this room would you do a threesome with?",
    "Who here do you secretly think has cheated?",
    "Who would you let dominate you completely for a night?",
    "Who here has the filthiest mind?",
    "Who here would you pay to watch?",
    "Who in this room would be the best fourth at an after-party?",
    "Who here would you cross every line for?",
    "Who is the best kisser you've actually kissed in this room?",
    "Who here do you think has hooked up with the most people in the last year?",
    "Who here is hiding the wildest secret?",
    "Who here would you let pick your outfit every day for a year if they pick what's underneath too?",
  ],
  extreme: [
    "Who here would you actually sleep with?",
    "Who's the freakiest in bed in this room?",
    "Who here do you think is secretly into something wild?",
    "Who would be the best threesome partner in this group?",
    "Who's the loudest in bed?",
    "Who has the biggest body count here?",
    "Who would you let dominate you?",
    "Who would you want to watch you?",
    "Who's most likely to cheat on their partner?",
    "Who here do you think has seen the most action this year?",
  ],
};
