import type { Intensity } from "../types";

// Short, punchy questions for the hot-seat timer round. A run draws 5-8
// prompts at once from the pool and flashes them on screen.

export const prompts: Record<Intensity, string[]> = {
  mild: [
    "Worst habit you have?",
    "Last lie you told?",
    "Dream job at 8 years old?",
    "Most used emoji?",
    "Worst date you've been on?",
    "Favorite conspiracy theory?",
    "Last thing you googled?",
    "Weirdest fear?",
    "Nickname you hated as a kid?",
    "Pettiest grudge you hold?",
    "Show you quit halfway through?",
    "Last thing you bought online?",
    "Celebrity you'd want to meet?",
    "Favorite comfort food?",
    "Longest you've gone without sleep?",
    "Best prank you've pulled?",
  ],
  spicy: [
    "Last person you sexted?",
    "First person you ever kissed?",
    "Biggest turn-on?",
    "Biggest turn-off?",
    "Wildest place you've made out?",
    "Celebrity you'd hook up with?",
    "Last person who broke your heart?",
    "Worst pickup line that worked?",
    "Kink you're curious about?",
    "Ex you'd hook up with again?",
    "Hottest DM in your inbox?",
    "First crush?",
    "Weirdest dream you've had?",
    "Longest you've been single?",
    "Someone in this room you've thought about?",
    "Last lie told to a lover?",
  ],
  extreme: [
    "Hottest sex of your life — one line?",
    "Kinkiest thing you've done?",
    "Person in this room you'd sleep with?",
    "Last time you touched yourself?",
    "Body part you're best at using?",
    "Wildest place you've had sex?",
    "Someone you'd never admit to sleeping with?",
    "Filthiest thing you've said mid-act?",
    "Most people in one night?",
    "Dirty dream about someone here?",
    "Favorite position — say it out loud?",
    "Time you faked it?",
    "Fantasy you haven't told anyone?",
    "Last nude in your camera roll — who for?",
    "Kink that shocks you about yourself?",
    "Person you'd ruin your reputation for?",
  ],
  chaos: [
    "Filthiest thing you've done for free?",
    "Someone in this room you'd fuck tonight?",
    "Most toys you've used at once?",
    "Last person who made you cum?",
    "Craziest place you've cum?",
    "Whose name have you moaned by mistake?",
    "Hardest you've ever been choked or choked someone?",
    "Paid how much for a sex act?",
    "Filthiest thing you've recorded?",
    "Kink you'd never tell your partner?",
    "Two people here for a threesome — who?",
    "Cheating confession — one sentence?",
    "Weirdest thing you've put in your mouth?",
    "Porn search that scares you?",
    "Position nobody's hit right except one person?",
    "Most degrading thing you've asked for?",
  ],
};
