import type { Intensity } from "../types";

// Reverse Charades: one guesser, the group silently acts out the prompt.
// Needs to be something visually actable with bodies and faces.

export const prompts: Record<Intensity, string[]> = {
  mild: [
    "A wedding ceremony",
    "A job interview going badly",
    "Teaching a kid to ride a bike",
    "A dog park fight",
    "A crowded elevator",
    "A yoga class",
    "Running from a bee",
    "A surprise birthday party",
    "An awkward first date",
    "Waiting in line at the DMV",
    "A zombie invasion",
    "A silent disco",
    "A magic show",
    "A fire drill",
    "A haunted house tour",
    "A fashion runway",
  ],
  spicy: [
    "A first kiss going wrong",
    "A bachelorette party",
    "A club at 2am",
    "A bartender flirting for tips",
    "A hot tub argument",
    "A make-out session interrupted",
    "A pole dance class",
    "A blind date",
    "A wedding proposal",
    "A drunken karaoke",
    "A couple's fight in public",
    "An Instagram photoshoot",
    "A failing stripper audition",
    "A hotel lobby hookup",
    "A bachelor party",
  ],
  extreme: [
    "A strip club regular",
    "A dominatrix session",
    "A threesome setting up",
    "A sex shop employee training",
    "A couple trying a new position",
    "A dungeon master running a scene",
    "An OnlyFans shoot",
    "A fetish convention",
    "A dirty talk class",
    "A sex therapist's office",
    "A lap dance",
    "A porn set between takes",
    "A swingers' party mixer",
    "A tantra workshop",
    "A burlesque finale",
  ],
  chaos: [
    "A sex cult ritual",
    "An orgy photoshoot",
    "A cuckold confession booth",
    "A BDSM rehearsal gone off-script",
    "A group sex tape edit session",
    "A safe-word conference",
    "A nude hot yoga class",
    "A sex robot malfunction",
    "A demon negotiating a threesome",
    "A vampire seduction",
    "A zero-gravity orgy",
    "A drag nun bachelorette",
    "A sex dungeon tour gone wrong",
    "A kink convention emergency",
    "A reality-TV elimination ceremony with nudity",
  ],
};
