import type { Intensity } from "../types";

// The Imposter (text Spyfall-style): the group all sees a secret location.
// One player is the imposter — they see "?" instead. Players take turns asking
// each other vague questions about "this place" and try to sniff out the
// imposter without tipping them off to the actual location.

export const locations: Record<Intensity, string[]> = {
  mild: [
    "a museum",
    "a wedding reception",
    "a casino floor",
    "a gym locker room",
    "a karaoke bar",
    "a funeral parlor",
    "a summer camp cabin",
    "a cruise ship buffet",
    "an airplane in turbulence",
    "a public library",
    "a haunted house",
    "a farmer's market",
    "a hospital waiting room",
    "a police interrogation room",
    "a yoga retreat",
    "a hair salon",
  ],
  spicy: [
    "a first-date restaurant",
    "a house party you weren't invited to",
    "a hotel room after a hookup",
    "a bachelorette party",
    "a singles mixer",
    "a speed-dating event",
    "a concert front row",
    "a late-night diner after 2am",
    "a Tinder date gone long",
    "a co-ed sauna",
    "a fraternity kitchen at 4am",
    "a kink-curious book club",
    "a festival campsite",
    "a rooftop pool party",
    "a limo on prom night",
  ],
  extreme: [
    "a sex club",
    "a strip club private room",
    "a porn set",
    "a sex dungeon",
    "a BDSM party",
    "an OnlyFans house shoot",
    "a swingers' retreat",
    "a brothel waiting area",
    "a polyamorous family reunion",
    "a dominatrix's office",
    "a tantric workshop",
    "a sugar-daddy dating convention",
    "a fetish con after-hours",
    "a hook-up spot in a public park",
    "a sex-therapy group session",
  ],
  chaos: [
    "an alien orgy on Mars",
    "a sex-cult initiation",
    "a centaur strip club",
    "a vampire brothel",
    "a sex tape set that's actually a horror film",
    "a haunted sex dungeon",
    "a demon's tantra retreat",
    "a polyamorous exorcism",
    "a zero-gravity sex marathon",
    "a ghost threesome in an old mansion",
    "an AI sex-robot showroom",
    "a time-traveler's orgy at the library of Alexandria",
    "a sex-toy factory tour gone wrong",
    "a purgatory-themed swingers party",
    "a kink convention held in a nunnery",
  ],
};
