import type { Intensity } from "../types";

// Thumbs Up / Thumbs Down prompts. Everyone votes simultaneously,
// reveal shows the split. Either direction can be a drink rule.

export const prompts: Record<Intensity, string[]> = {
  mild: [
    "Pineapple on pizza?",
    "Getting out of bed before 7am?",
    "Reality TV?",
    "Texting your ex 'happy birthday'?",
    "Flying in the middle seat?",
    "Karaoke sober?",
    "Telling a friend their partner sucks?",
    "Tattooing on vacation?",
    "Moving in with a partner after 3 months?",
    "Posting Instagram stories every day?",
    "Open-faced sandwiches?",
    "Karaoke for work events?",
    "Reply-all to the whole company?",
    "Calling instead of texting?",
    "Using your real name on dating apps?",
  ],
  spicy: [
    "Hooking up on a first date?",
    "Dating your best friend's ex?",
    "Sending nudes you'd be OK with leaking?",
    "Swiping with your partner's phone?",
    "Kissing at a wedding you met at?",
    "Drinking on a Monday?",
    "Ghosting after three great dates?",
    "Going home with someone tonight if you could?",
    "Sleeping with a coworker?",
    "Flirting with the bartender to avoid a tab?",
    "Telling your partner your number?",
    "Cuddling with a friend you've hooked up with?",
    "Reading your partner's texts?",
    "Having drinks with your ex just to catch up?",
    "Hooking up with someone in this room?",
  ],
  extreme: [
    "Threesome with your partner's sibling?",
    "Group sex at a retreat?",
    "Paying for sex once?",
    "Being paid for sex once?",
    "Recording yourself during sex?",
    "Sending a full nude to a coworker?",
    "Sleeping with your therapist after your last session?",
    "OnlyFans if it paid rent?",
    "Kissing someone in this room for a $500 bet?",
    "Going home with your Uber driver?",
    "Hooking up in your parents' house?",
    "Opening your relationship?",
    "Swapping partners with another couple for a night?",
    "Getting choked / choking someone in bed?",
    "Role-playing as your partner's celebrity crush?",
  ],
  chaos: [
    "A foursome with two exes?",
    "Being filmed by a stranger mid-act?",
    "Eye contact during?",
    "Sex with someone three rooms away right now?",
    "Letting your partner sleep with someone else if you watched?",
    "Losing your job for a perfect night?",
    "A sugar arrangement?",
    "Hooking up at the funeral?",
    "Choosing your worst ex for one last night?",
    "Sex on hallucinogens?",
    "An orgy with your best friends?",
    "Getting paid in cash mid-way through?",
    "Fucking your worst enemy?",
    "No toys for a year — or no partners for a year?",
    "Your partner hooking up with someone in this room?",
  ],
};
