import type { Intensity } from "../types";

export const truths: Record<Intensity, string[]> = {
  mild: [
    "What's the most embarrassing song on your playlist — no scrolling, open it now.",
    "What's the last lie you told, and who bought it?",
    "What's your biggest irrational fear, and when did it start?",
    "Who in this room would you trade lives with for a day, and why?",
    "What's a weird habit you do alone that nobody's caught?",
    "What's the pettiest reason you've cut someone off?",
    "What's your worst first-date horror story?",
    "What's something you pretend to enjoy just to fit in?",
    "What's the dumbest thing you've cried about as an adult?",
    "What's a compliment you secretly wish someone would give you?",
    "Who was your weirdest childhood crush — celeb or cartoon counts?",
    "What's the most you've ever spent impulse-buying something stupid?",
    "What's a small lie you tell on every job interview?",
    "What's the last thing you googled that you'd be embarrassed about?",
    "Who in this room gives the best advice — and who gives the worst?",
    "What's a compliment you've gotten that you didn't know how to handle?",
    "What's the most childish thing you still do?",
    "If everyone here voted you 'most likely to…' something, what would it be?",
  ],
  spicy: [
    "What's the most scandalous photo in your camera roll? Describe it.",
    "Who in this room have you caught yourself thinking about?",
    "What's the worst bedroom story you're willing to share?",
    "Who's the last person you stalked on Instagram and why?",
    "What's the hottest DM you've ever sent — word for word?",
    "What's your real body count — and how close is the number you tell people?",
    "Have you ever hooked up with someone in a friend group? Spill.",
    "What's a kink you're curious about but haven't tried?",
    "What's the wildest place you've made out?",
    "Who's the last person you sexted, and what was the last line?",
    "What's the longest dry spell you've had — and what broke it?",
    "What's a rumor about you that turned out to be true?",
    "What's the worst first-kiss you've ever had?",
    "Tell us about the last time you caught feelings you didn't want.",
    "What's your go-to fake excuse when you ghost someone?",
    "What's a pickup line that's actually worked on you?",
    "If you had to sleep with one person in this room, who?",
    "What's the most embarrassing reason you've been dumped?",
  ],
  extreme: [
    "Who in this room would you take home tonight if it had to happen?",
    "Describe the wildest hookup of your life in full detail.",
    "What's the kinkiest thing you've done — and who with?",
    "Have you ever cheated? Full story, names optional.",
    "What's the filthiest thing you've ever searched online?",
    "Who in this room have you fantasized about — and what happens in it?",
    "What's your hardest kink — the one you don't admit out loud?",
    "When was the last time you touched yourself, and who were you thinking about?",
    "Describe the best sex of your life. No skipping the details.",
    "Have you ever been filmed — on purpose or otherwise? Does it still exist?",
    "What's the most people you've been with in one night?",
    "What's a secret about your sex life that would shock the people closest to you?",
    "What's something you've done sexually that you'd never admit sober?",
    "Who here do you think would be the best in bed — and why?",
    "What's the most expensive thing you've done or bought because someone turned you on?",
    "What's the closest you've come to getting caught doing something you shouldn't?",
    "Have you ever hooked up with someone just to get back at someone else?",
    "What's a line you said you'd never cross — and exactly how you crossed it?",
  ],
  chaos: [
    "Name every person in this room you've pictured naked, and rank them.",
    "Read the filthiest text on your phone out loud, right now, no previewing.",
    "Who here would you let ruin you for a night, zero strings?",
    "Describe the last time you finished yourself off — who, what, how.",
    "What's the hardest line you swore you'd never cross, and the exact night you did?",
    "What have you done in the last month that would end a friendship if anyone here found out?",
    "Who in this room do you want to kiss right now — and say why out loud.",
    "Describe your filthiest fantasy involving someone in this room, in real detail.",
    "What's your safe word? If you don't have one, pick it now in front of the group.",
    "Who was the last person you sent a nude to, and show the thread.",
    "What's the dirtiest thing anyone's ever said to you mid-act?",
    "What's a kink you have that would ruin your reputation if it leaked?",
    "Rank everyone in this room by how you'd want them, hottest to not.",
    "What's the messiest place you've ever gotten off — and who caught you if anyone?",
    "If you had to pick two people in this room for a threesome, who and why?",
    "What's a sexual regret you replay in your head?",
    "What's the wildest thing you've ever paid for — or been paid for?",
    "Describe something you've done that you haven't even told your closest friend.",
  ],
};

export const dares: Record<Intensity, string[]> = {
  mild: [
    "Text the 5th person in your contacts a single 🍆 and wait 30 seconds before explaining.",
    "Do your best impression of another player until someone guesses who it is.",
    "Let the player on your left post one story to your feed — no editing.",
    "Speak only in questions until your next turn.",
    "Show the last photo in your camera roll. No scrolling.",
    "Do 15 jumping jacks while singing the alphabet backwards.",
    "Call your mom (or closest family member) and tell her a random penguin fact like it's urgent.",
    "Let the group pick your next profile picture from your camera roll.",
    "Do a dramatic soap-opera reading of the last text thread you opened.",
    "Try to lick your own elbow for 30 seconds. Keep trying.",
    "Let the group choose one emoji — set it as your bio until tomorrow.",
    "Pick a random contact and send them a voice note of you humming 'happy birthday'.",
    "Do your worst accent for the next 3 rounds.",
    "Eat something from the kitchen the group picks — without complaining.",
    "Let the player across from you rearrange your home screen for 60 seconds.",
    "Do 20 seconds of interpretive dance to whatever song is playing.",
    "Tell a 30-second story using only words that start with the same letter.",
    "Post a selfie with the worst filter the group can find.",
  ],
  spicy: [
    "Give the player of your choice a 15-second slow lap dance. No skipping.",
    "Let someone write a word of their choice on your stomach in lipstick or marker.",
    "Take a shot off another player's neck, wrist, or collarbone — they pick where.",
    "Kiss the player to your right on the cheek. Make it linger three seconds.",
    "Show the last 'I miss you' (or equivalent) message you sent — no editing.",
    "Swap one piece of clothing with the player across from you. Keep it on for 3 rounds.",
    "Let another player send one flirty message from your phone to anyone they pick.",
    "Whisper something filthy into the ear of whoever the group chooses. Loud enough they react.",
    "Sit on another player's lap for the next 2 rounds.",
    "Demonstrate your best make-out technique on your own hand for 15 seconds.",
    "Tell the player on your right exactly what you find attractive about them.",
    "Let the group pick an emoji. Send it to your most recent ex with no context.",
    "Send your crush a 🔥 and only a 🔥. The group watches you hit send.",
    "Hold eye contact with the player of the group's choice for a full 30 seconds.",
    "Let another player pick a song — dance like nobody's watching for the chorus.",
    "Unlock your phone and hand it to the player on your left for 20 seconds. No watching.",
    "Let the group read the last three DMs you sent (pick the thread — or they do).",
    "Show the group your flirtiest selfie from this year.",
  ],
  extreme: [
    "Make out with the player of the group's choice for 20 seconds. Group counts.",
    "Remove one piece of clothing — group's pick. Stays off for 3 rounds.",
    "Give or receive a neck kiss from a player of the group's choice.",
    "Let another player blindfold you and feed you something. Guess what it is before you swallow.",
    "Let the group pose you however they want. One photo. It's the lock screen until morning.",
    "Sit on the lap of whoever the group chooses for the next round.",
    "Send a thirst trap to your most recent ex. Group approves the shot before it sends.",
    "Pick a player. Trade one piece of clothing with them — wear theirs the rest of the night.",
    "Let another player tie your wrists for the next 3 rounds.",
    "Act out a bedroom scene with a player of the group's choice. 30 seconds. No breaking character.",
    "Let someone in the room kiss any exposed patch of skin for 5 seconds. Their pick.",
    "Read the filthiest message you've ever sent — out loud, in character.",
    "Play your most replayed song and strip-tease to the first verse.",
    "Let the group rearrange your Tinder/Hinge bio. Live. No edits.",
    "Pick any player. Whisper exactly what you'd do to them if no one else was here.",
    "Handcuff (or tie) yourself to the player on your right until the next round ends.",
    "Let two players kiss your neck at the same time for 10 seconds.",
    "Demo your best move on a pillow for 20 seconds, eye contact with the group.",
  ],
  chaos: [
    "Pick someone in the room. Make out with them for 30 seconds, no hands.",
    "Let the group choose one piece of clothing. Remove it. Keep it off until the game ends.",
    "Sit on someone's lap for the rest of the game — group picks who.",
    "Let the group blindfold you. Three players kiss you somewhere. Guess who kissed where.",
    "Let the player across from you write their number on your body in lipstick. You leave it.",
    "Give the player of the group's choice a full 30-second lap dance. No laughing.",
    "Trade one piece of clothing with someone the group picks. Wear it the rest of the night.",
    "Whisper your filthiest thought to the player on your right — loud enough the group can describe their reaction.",
    "Let another player bind your wrists with something in the room for the next 4 rounds.",
    "Record a voice note of you saying something filthy to the last person you hooked up with. Group listens before you send.",
    "Take a body shot off whoever the group chooses — they pick where on the body too.",
    "Let the group pose you however they want. One photo. Lock screen until tomorrow morning.",
    "Give the group access to your DMs for 30 seconds. They read silently. You take whatever comes.",
    "Pick one player. Do anything they ask (within reason) for the next 2 rounds.",
    "Remove two pieces of clothing — group picks both.",
    "Let two players make out with you, one after the other, 10 seconds each. Rank them out loud.",
    "Send the last person who rejected you a voice note the group scripts.",
    "Let the group pick a position. Demonstrate it on the floor, fully clothed, 15 seconds.",
  ],
};
